blank_issues_enabled: true

title: LinkedIn-Bot
description: This is a bot that handles your LinkedIn.

tags:
  [
    "bot",
    "shell",
    "firebase",
    "selenium",
    "linkedin",
    "firestore",
    "webdriver",
    "automation",
    "linkedin-bot",
    "chromedriver",
    "shell-script",
    "webautomation",
    "selenium-webdriver",
    "automation-scripts",
    "linkedin-automator",
  ]
